name: 'Build'
on:
  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_TARGET: f7
  FBT_TOOLCHAIN_PATH: /runner/_work
  FBT_GIT_SUBMODULE_SHALLOW: 1

jobs:
  main:
    runs-on: [windows-latest]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: 'Build'
        id: build
        run: |
          $git_hash = git rev-parse --short $env:GITHUB_SHA
          echo "git_hash=$git_hash" >> $env:GITHUB_ENV
          ./fbt
          
      - name: Upload artifact
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: firmware-${{ github.ref_name }}-${{ env.git_hash }}.dfu
          path: build/f7-firmware-D/firmware.dfu